In [1]:
import pandas as pd
import os

In [8]:
df = pd.read_csv( "exoplanet_data.csv")
df.head()

,koi_disposition,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,CONFIRMED,0,0,0,0,54.418383,2.479000e-04,-2.479000e-04,162.513840,0.003520,...,-81,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,FALSE POSITIVE,0,1,0,0,19.899140,1.490000e-05,-1.490000e-05,175.850252,0.000581,...,-176,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
2,FALSE POSITIVE,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,...,-174,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
3,CONFIRMED,0,0,0,0,2.525592,3.760000e-06,-3.760000e-06,171.595550,0.001130,...,-211,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509
4,CONFIRMED,0,0,0,0,4.134435,1.050000e-05,-1.050000e-05,172.979370,0.001900,...,-232,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714

In [7]:
df[df.kepid.duplicated()]

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
6,7,10872983,K00756.02,Kepler-228 c,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-232.0,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714
7,8,10872983,K00756.03,Kepler-228 b,CONFIRMED,CANDIDATE,0.992,0,0,0,...,-232.0,4.486,0.054,-0.229,0.972,0.315,-0.105,296.28613,48.224670,15.714
22,23,10601284,K00749.02,Kepler-226 b,CONFIRMED,CANDIDATE,0.980,0,0,0,...,-77.0,4.440,0.098,-0.045,0.910,0.057,-0.086,292.37613,47.880989,15.416
23,24,10601284,K00749.03,Kepler-226 d,CONFIRMED,CANDIDATE,0.971,0,0,0,...,-77.0,4.440,0.098,-0.045,0.910,0.057,-0.086,292.37613,47.880989,15.416
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9544,9545,10467815,K03191.02,NaN,CANDIDATE,CANDIDATE,0.598,0,0,0,...,-466.0,3.822,0.351,-0.162,3.218,0.977,-1.466,290.81604,47.682892,11.471
9545,9546,7429287,K04260.03,NaN,FALSE POSITIVE,FALSE POSITIVE,0.047,1,0,0,...,-42.0,4.070,0.013,-0.011,1.406,0.050,-0.021,286.39584,43.075821,11.443
9546,9547,7429287,K04260.04,NaN,CANDIDATE,CANDIDATE,0.971,0,0,0,...,-42.0,4.070,0.013,-0.011,1.406,0.050,-0.021,286.39584,43.075821,11.443
9547,9548,11775507,K06245.03,NaN,FALSE POSITIVE,FALSE POSITIVE,0.174,1,0,0,...,-252.0,4.257,0.153,-0.170,1.260,0.362,-0.241,297.51782,49.917702,12.431
9548,9549,6768616,K06765.02,NaN,FALSE POSITIVE,FALSE POSITIVE,0.294,1,0,0,...,-200.0,4.434,0.084,-0.210,0.994,0.296,-0.127,289.04434,42.280022,15.154